### ISSUE TITLE
Error ... or not ? Installation on Ubuntu 12.04

### ISSUE THREAD

**Issue by Baanor** [G-Ray/candyflix#11]
Hi, first of all thanks for your work 

I've tried to make it work on Ubuntu 12.04.

I can launch candyflix.js without error... but with nothing either, just a blank prompt in is loneliness.
To do that i need to kill Nginx process en port 3000, without it end-up with error :

 events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Server.listen.Server.attach (/usr/share/nginx/www/candyflix/app/node_modules/socket.io/lib/index.js:214:9)
    at Object.<anonymous> (/usr/share/nginx/www/candyflix/app/candyflix.js:103:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12) 

Am i on the good direction or everything i've done is wrong?

```
                                                                        Merci.
```

**Comment by G-Ray** [comment]
It seems you have configured you nginx server to listen on 3000, that's why you have this "EADDRINUSE" error. Configure nginx to listen on another port.
Once candyflix is started, and the proxy is set, just open a browser on the port nginx listen to ;)
