### ISSUE TITLE
Error on Playing movies please help

### ISSUE THREAD

**Issue by cyber-cliff** [G-Ray/candyflix#14]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn peerflix ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by G-Ray** [comment]
Hi !
I think you have not installed peerflix on your system. You can do so either with your package manager, or by running : "npm install -g peerflix"

**Comment by cyber-cliff** [comment]
yeah i already installed on my system. by the way im using windows server environment.

**Comment by G-Ray** [comment]
I don't know much about windows environment. Is peerflix in the PATH ? (e.g can you start peerflix from the command line ?)
